group: travis_latest

sudo: required
services:
  - docker

language: python
cache:
  pip: true
  directories:
    - $HOME/.pip-cache/

python:
  - 3.6

stages:
  - test
  - docs
  - name: dockerbuild
    if: branch = dev #@TODO to map it to production branch

env:
  jobs:
    - DOCKER_ORG: openmined

install:
  - sudo apt-get update
  - hash -r
  - pip3 install -r requirements.txt --cache-dir $HOME/.pip-cache > build.log
  - pip3 install flake8 --cache-dir $HOME/.pip-cache
  #- pip3 install flake8-docstrings
  - pip3 install flake8-comprehensions --cache-dir $HOME/.pip-cache
  - pip3 install pep8-naming --cache-dir $HOME/.pip-cache
  - pip3 install -r dev-requirements.txt --cache-dir $HOME/.pip-cache >> build.log
before_script:
  # stop the build if there are Python syntax errors or undefined
  # names
  - flake8 --config=.flake8 .
  - black --check --verbose .
  # exit-zero treats all errors as warnings.
  # diverting from the standard 79 character line length in
  # accordance with this:
  # https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds
  - flake8 . --count --exit-zero --statistics --select=E,F,W,C90
jobs:
  allow_failures:
    - python: nightly
    - python: pypy
    - python: pypy3
  include:
    - stage: test
      name: 'Test Coverage'
      script:
        - coverage run -m pytest -v
    - stage: test
      name: 'Document Generation'
      script:
        - cd docs
        - make html
        # - if grep -q "Traceback (most recent call last):" nb_to_md.txt; then false; else true; fi
    - stage: dockerbuild
      name: 'Docker build openmined/grid-gateway'
      script:
        - docker build -t $DOCKER_ORG/grid-gateway ./gateway/
        - docker images $DOCKER_ORG/grid-gateway
    - stage: dockerbuild
      name: 'Docker build openmined/grid-node'
      script:
        - docker build -t $DOCKER_ORG/grid-node ./app/websocket/
        - docker images $DOCKER_ORG/grid-node

notifications:
  on_success: change
  # `always` will be the setting below once code changes slow down
  on_failure: change
