version: '3'
services:
  network:
    image: openmined/grid-network:production
    build: ./apps/network
    environment:
      - PORT=5000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasenetwork.db
    ports:
      - 5000:5000
  alice:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Alice
      - ADDRESS=http://alice:3000/
      - PORT=3000
      - NETWORK=http://network:5000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 3000:3000

  bob:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Bob
      - ADDRESS=http://bob:3001/
      - PORT=3001
      - NETWORK=http://network:5000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 3001:3001

  charlie:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Charlie
      - ADDRESS=http://charlie:3002/
      - PORT=3002
      - NETWORK=http://network:5000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 3002:3002
  dan:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Dan
      - ADDRESS=http://dan:3003/
      - PORT=3003
      - NETWORK=http://network:5000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 3003:3003

  jupyter:
    image: openmined/pysyft-notebook
    depends_on:
      - 'dan'
    ports:
      - 8888:8888
    volumes:
      - ./examples:/workspace/examples
