version: '3'
services:
    gateway:
        image: gateway:latest
        environment:
                - PORT=8080
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databaseGateway.db
        ports:
                - "8080:8080"
        network_mode: "host"
    bob:
        image: node:latest
        environment:
                - GRID_NETWORK_URL=http://localhost:8080
                - ID=Bob
                - ADDRESS=http://localhost:3000/
                - DATABASE_URL=sqlite:///databaseBob.db
                - PORT=3000
        depends_on:
                - "gateway"
        network_mode: "host"
    alice:
        image: node:latest
        environment:
                - GRID_NETWORK_URL=http://localhost:8080
                - ID=Alice
                - ADDRESS=http://localhost:3001/
                - DATABASE_URL=sqlite:///databaseAlice.db
                - PORT=3001
        depends_on:
                - "gateway"
        network_mode: "host"
    bill:
        image: node:latest
        environment:
                - GRID_NETWORK_URL=http://localhost:8080
                - ID=Bill
                - ADDRESS=http://locahost:3002/
                - DATABASE_URL=sqlite:///databaseBill.db
                - PORT=3002
        depends_on:
                - "gateway"
        network_mode: "host"
