version: '3'
services:
  network:
    image: openmined/grid-network:production
    build: ./apps/network
    environment:
      - PORT=7000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasenetwork.db
    ports:
      - 7000:7000
  bob:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Bob
      - ADDRESS=http://bob:5000/
      - PORT=5000
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5000:5000
  alice:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Alice
      - ADDRESS=http://alice:5001/
      - PORT=5001
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5001:5001
  bill:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Bill
      - ADDRESS=http://bill:5002/
      - PORT=5002
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5002:5002
  james:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=James
      - ADDRESS=http://james:5003/
      - PORT=5003
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5003:5003
