apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: node:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: ADDRESS
            value: http://localhost:3000/
          - name: DATABASE_URL
            value: sqlite:///databaseNode.db
          - name: GRID_NETWORK_URL
            value: http://gateway:5000
          - name: ID
            value: Node
          - name: PORT
            value: "3000"
      restartPolicy: Always
