- hosts: hosts
  remote_user: ubuntu
  gather_facts: False
  pre_tasks:
    - name: Install python
      raw: bash -c "test -e /usr/bin/python || (sudo apt -qqy update && sudo apt install -qqy python-minimal python2.7)"
      register: output
      changed_when: output.stdout
    - setup: # aka gather_facts
  
  tasks:
    - name: Update apt
      apt:
        upgrade: yes
        update_cache: yes
      become: true
    
    - name: Install pip
      apt:
        name: python-pip
      become: true

    - name: Install python docker
      pip:
        name: docker-py
      become: true
    
    - docker_container:
        name: grid_gateway_instance
        image: openmined/grid-gateway:latest
        env:
            PORT: "5000"
            SECRET_KEY: "ineedtoputasecrethere" 
            DATABASE_URL: "sqlite:///databasegateway.db"
        network_mode: "host"
      become: true

    - docker_container:
        name: redis
        image: redis:latest
        network_mode: "host"
      become: true
    
    - docker_container:
        name: bob
        image: openmined/grid-node:latest
        env:
            GRID_NETWORK_URL: "http://localhost:5000"
            ID: "Bob"
            ADDRESS: "http://localhost:3000/"
            REDISCLOUD_URL: "redis:///localhost:6379"
            PORT: "3000"
        network_mode: "host"
      become: true
    
    - docker_container:
        name: alice
        image: openmined/grid-node:latest
        env:
            GRID_NETWORK_URL: "http://localhost:5000"
            ID: "Alice"
            ADDRESS: "http://localhost:3001/"
            REDISCLOUD_URL: "redis:///localhost:6379"
            PORT: "3001"
        network_mode: "host"
      become: true
    
    - docker_container:
        name: bill
        image: openmined/grid-node:latest
        env:
            GRID_NETWORK_URL: "http://localhost:5000"
            ID: "Bill"
            ADDRESS: "http://localhost:3002/"
            REDISCLOUD_URL: "redis:///localhost:6379"
            PORT: "3002"
        network_mode: "host"
      become: true
    
    - docker_container:
        name: james
        image: openmined/grid-node:latest
        env:
            GRID_NETWORK_URL: "http://localhost:5000"
            ID: "James"
            ADDRESS: "http://localhost:3003/"
            REDISCLOUD_URL: "redis:///localhost:6379"
            PORT: "3003"
        network_mode: "host"
      become: true
